* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
MATERIAL          5.   10.8117      2.46                              BORON
MATERIAL         15. 30.973762     1.823                              PHOSPHO
MATERIAL         16.   32.0655      1.96                              SULFUR
MATERIAL         24.   51.9961      7.18                              CHROMIUM
MATERIAL         25. 54.938045      7.47                              MANGANES
MATERIAL         42.     95.96     10.28                              MOLYBDEN
MATERIAL         75.   186.207     21.04                              RHENIUM
MATERIAL         63.   151.964     5.264                              EUROPIUM
MATERIAL         19.   39.0983     0.862                              POTASSIU
MATERIAL                            19.7                              TARMAT
MATERIAL                            7.98                              STAINLES
MATERIAL                             6.4                              LIGHTSUS
MATERIAL                            7.15                              CASTIRON
MATERIAL         0.0       0.0        1.                              WATER1
MATERIAL                              1.                              LIQSEAL
MATERIAL                            2.43                              CONCRETE
MATERIAL                            2.22                              CONSHLD
MATERIAL                            8.94                              Copper
MATERIAL                            19.7                              WShield
MATERIAL                            7.87                              LOWCIRON
MATERIAL         27.                 8.9                              COBALT
*
* --+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
MATERIAL                           2.700                              ROCKMEAS
MATERIAL                           2.700                              ROCKKITA
MATERIAL                           2.700                              ROCKJG3
MATERIAL                           2.700                              ROCKJA3
* --+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
MATERIAL         23.   50.9415        6.                              VANADIUM
MATERIAL         19.   39.0983     7.140                              ZINC
MATERIAL         21.   44.9559     2.985                              SCANDIUM
MATERIAL         24.   51.9961     7.190                              CHROMIUM
MATERIAL         55.  132.9050     1.930                              CESIUM
* --+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
COMPOUND       -0.75  TUNGSTEN     -0.25   RHENIUM    -5E-05    COBALTTARMAT
COMPOUND          2.  HYDROGEN        1.    OXYGEN                    WATER
*
*
* Rock from Terunuma
*
*
* ROCKMEAS
*  
* --+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
COMPOUND    -.495361    OXYGEN -.2907554   SILICON  -.001615  HYDROGENROCKMEAS
COMPOUND    -.001185   PHOSPHO     -.082  ALUMINUM     -.033      IRONROCKMEAS
COMPOUND       -.032   CALCIUM     -.025    SODIUM     -.025  POTASSIUROCKMEAS
COMPOUND       -.011  MAGNESIU    -.0023  TITANIUM   -6.5E-4  MANGANESROCKMEAS
COMPOUND   -1.000E-5  SCANDIUM   -8.5E-6  CHROMIUM   -3.5E-6    CESIUMROCKMEAS
COMPOUND     -7.7E-5  VANADIUM   -2.1E-5      ZINC   -1.0E-4    COBALTROCKMEAS
COMPOUND    -10.0E-6  EUROPIUM                                        ROCKMEAS
*COMPOUND     -7.7E-5  VANADIUM   -2.1E-5      ZINC   -1.3E-5    COBALTROCKMEAS
*COMPOUND   -7.000E-7  EUROPIUM                                        ROCKMEAS
*
* ROCKKITA
*
* --+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
COMPOUND      -.6248    OXYGEN    -.2216   SILICON -3.000E-4   PHOSPHOROCKKITA
COMPOUND      -.0663  ALUMINUM    -.0166      IRON     -.028   CALCIUMROCKKITA
COMPOUND      -.0199    SODIUM    -.0114  POTASSIU    -.0096  MAGNESIUROCKKITA
COMPOUND      -.0014  TITANIUM -4.000E-4  MANGANES                    ROCKKITA
*
* Rock JA3, JG3 taken from https://gbank.gsj.jp/geostandards/welcomej.html
*
*
* ROCKJG3
*
* --+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
COMPOUND   -.4836372    OXYGEN -.3151468   SILICON -9.417E-4  HYDROGENROCKJG3
COMPOUND   -5.334E-4   PHOSPHO -.0820778  ALUMINUM -.0256036      IRONROCKJG3
COMPOUND   -.0264216   CALCIUM -.0294324    SODIUM  -.021957  POTASSIUROCKJG3
COMPOUND   -.0108153  MAGNESIU  -.002882  TITANIUM -5.509E-4  MANGANESROCKJG3
*
* ROCKJA3
*
* --+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
COMPOUND   -.4706007    OXYGEN -.2922598   SILICON -3.483E-4  HYDROGENROCKJA3
COMPOUND   -5.082E-4   PHOSPHO -.0826785  ALUMINUM -.0457709      IRONROCKJA3
COMPOUND    -.044776   CALCIUM -.0237601    SODIUM -.0117521  POTASSIUROCKJA3
COMPOUND   -.0225245  MAGNESIU  -.004212  TITANIUM -8.087E-4  MANGANESROCKJA3
* Concrete  with Co 100ppm, Eu 10ppm
*
COMPOUND     -0.0096  HYDROGEN    -0.029     BORON   -0.0536    CARBONCONCRETE
COMPOUND      -0.513    OXYGEN   -0.0042  MAGNESIU   -0.0079  ALUMINUMCONCRETE
COMPOUND      -0.157   SILICON   -0.0042    SULFUR     -0.23   CALCIUMCONCRETE
COMPOUND      -0.005      IRON    -1E-04    COBALT     -1E-5  EUROPIUMCONCRETE
*COMPOUND      -0.005      IRON    -5E-05    COBALT                    CONCRETE
*
* Shield Concrete by Morikawa, Density 0.22(?)g/cm3
* Wt%, H=0.19, O=46.3, Na=1.66, Mg=0.50, Al=8.95, Si=25.6, K=1.06
*     Ca=9.18, Fe=6.12, Co=0.01, Eu=0.001
*    Standard Concrete would be Co=0.002, Eu=0.0002
*
* potassium
COMPOUND       -0.19  HYDROGEN     -46.3    OXYGEN     -1.66    SODIUMCONSHLD
COMPOUND       -0.50  MAGNESIU     -8.95  ALUMINUM     -25.6   SILICONCONSHLD
COMPOUND       -1.06  POTASSIU     -9.18   CALCIUM     -6.12      IRONCONSHLD
COMPOUND      -0.002    COBALT   -0.0002  EUROPIUM     -1E-5  EUROPIUMCONSHLD
*COMPOUND      -0.002    COBALT   -0.0002  EUROPIUM     -1E-5  EUROPIUMCONSHLD
*
* Stainless-Steel SUS316LN (Same as fluka's Steel316LN )+0.02Mo
* Fe65%,Cr18%,Ni11%,Mn1.9%,Si0.97%,Mo1.9%,P0.03%,S0.29%,C0.29%
*
COMPOUND    -0.67145      IRON    -0.185  CHROMIUM   -0.1125    NICKELSTAINLES
COMPOUND       -0.02  MANGANES     -0.01   SILICON  -0.00045   PHOSPHOSTAINLES
COMPOUND     -0.0003    SULFUR   -0.0003    CARBON    -0.020  MOLYBDENSTAINLES
COMPOUND     -0.0001    COBALT                                        STAINLES
*
* Light SUS for1 the Target rotator structure
*
COMPOUND    -0.67145      IRON    -0.185  CHROMIUM   -0.1125    NICKELLIGHTSUS
COMPOUND       -0.02  MANGANES     -0.01   SILICON  -0.00045   PHOSPHOLIGHTSUS
COMPOUND     -0.0003    SULFUR   -0.0003    CARBON    -0.020  MOLYBDENLIGHTSUS
COMPOUND     -0.0001    COBALT                                        LIGHTSUS
*
* Liquid Seal material
*
COMPOUND     -85.700    CARBON   -14.300  HYDROGEN                    LIQSEAL
*
* Cast Iron UNS F33100
*
COMPOUND     -0.0365    CARBON  -0.00334  MANGANES -0.000575   PHOSPHOCASTIRON
COMPOUND      -0.024   SILICON   -0.0002    SULFUR -0.935835      IRONCASTIRON
COMPOUND      -5E-05    COBALT                                        CASTIRON
*
* Wshield
*
COMPOUND         -1.  TUNGSTEN    -5E-05    COBALT                    WShield
*
* Iron for Return yoke : Laminated pure iron
* Product of Tokusyu-Kinzoku Excel
* Ref: https://www.tokkin.co.jp/materials/common_steel/suy-1
*
COMPOUND      -0.004    CARBON     -0.01   SILICON    -0.170  MANGANESLOWCIRON
COMPOUND      -0.010   PHOSPHO    -0.005    SULFUR  -0.99801      IRONLOWCIRON
COMPOUND     -0.0001    COBALT                                        LOWCIRON
*
* Copper
COMPOUND         -1.    COPPER    -5E-05    COBALT                    Copper
MAT-PROP                            297.    COBALT
MAT-PROP         40.                        COBALT                    DPA-ENER
MAT-PROP         40.                        Copper                    DPA-ENER
MAT-PROP         40.                        TARMAT                    DPA-ENER
STERNHEI      4.2601   -0.0187     3.179   0.14474    2.9502      0.12COBALT
*
LOW-MAT     ALUMINUM       13.       27.      296.       0.0       0.0ALUMINUM
LOW-MAT     TITANIUM       22.       -2.      296.       0.0       0.0TITANIUM
*
