* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
MATERIAL          5.   10.8117      2.46                              BORON
MATERIAL         15. 30.973762     1.823                              PHOSPHO
MATERIAL         16.   32.0655      1.96                              SULFUR
MATERIAL         24.   51.9961      7.18                              CHROMIUM
MATERIAL         25. 54.938045      7.47                              MANGANES
MATERIAL         42.     95.96     10.28                              MOLYBDEN
MATERIAL         75.   186.207     21.04                              RHENIUM
MATERIAL                            19.7                              TARMAT
MATERIAL                            7.98                              STAINLES
MATERIAL                             6.4                              LIGHTSUS
MATERIAL                            7.15                              CASTIRON
MATERIAL         0.0       0.0        1.                              WATER
MATERIAL                              1.                              LIQSEAL
MATERIAL                            2.43                              CONCRETE
MATERIAL                            8.94                              Copper
MATERIAL                            19.7                              WShield
COMPOUND       -0.75  TUNGSTEN     -0.25   RHENIUM    -5E-05    COBALTTARMAT
COMPOUND          2.  HYDROGEN        1.    OXYGEN                    WATER
*
* Concrete
*
COMPOUND     -0.0096  HYDROGEN    -0.029     BORON   -0.0536    CARBONCONCRETE
COMPOUND      -0.513    OXYGEN   -0.0042  MAGNESIU   -0.0079  ALUMINUMCONCRETE
COMPOUND      -0.157   SILICON   -0.0042    SULFUR     -0.23   CALCIUMCONCRETE
COMPOUND      -0.005      IRON    -5E-05    COBALT                    CONCRETE
*
* Stainless-Steel SUS316
*
COMPOUND     -0.0008    CARBON     -0.01   SILICON     -0.02  MANGANESSTAINLES
COMPOUND    -0.00045   PHOSPHO   -0.0003    SULFUR     -0.16  CHROMIUMSTAINLES
COMPOUND        -0.1    NICKEL     -0.02  MOLYBDEN   -68.845      IRONSTAINLES
COMPOUND     -0.0001    COBALT                                        STAINLES
*
* Light SUS for the Target rotator structure
*
COMPOUND     -0.0008    CARBON     -0.01   SILICON     -0.02  MANGANESLIGHTSUS
COMPOUND    -0.00045   PHOSPHO   -0.0003    SULFUR     -0.16  CHROMIUMLIGHTSUS
COMPOUND        -0.1    NICKEL     -0.02  MOLYBDEN   -68.845      IRONLIGHTSUS
COMPOUND     -0.0001    COBALT                                        LIGHTSUS
*
* Liquid Seal material
*
COMPOUND     -85.700    CARBON   -14.300  HYDROGEN                    LIQSEAL
*
* Cast Iron UNS F33100
*
COMPOUND     -0.0365    CARBON  -0.00334  MANGANES -0.000575   PHOSPHOCASTIRON
COMPOUND      -0.024   SILICON   -0.0002    SULFUR  -93.5385      IRONCASTIRON
COMPOUND      -5E-05    COBALT                                        CASTIRON
*
* Wshield
*
COMPOUND         -1.  TUNGSTEN    -5E-05    COBALT                    WShield
*
* Copper
COMPOUND         -1.    COPPER    -5E-05    COBALT                    Copper
MATERIAL         27.                 8.9                              COBALT
MAT-PROP                            297.    COBALT
MAT-PROP         40.                        COBALT                    DPA-ENER
STERNHEI      4.2601   -0.0187     3.179   0.14474    2.9502      0.12COBALT
*
LOW-MAT     ALUMINUM       13.       27.      296.       0.0       0.0ALUMINUM
LOW-MAT     TITANIUM       22.       -2.      296.       0.0       0.0TITANIUM
*
