* ****
* Run scenario,
* ****
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
