* ****
* Run scenario for 20 year operation
* ****
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*      1C = 6.24153E18 electrons
*     2.4 nC/bunch
*   1312 (2625) bunches/pulse
*      5 pulse/sec
*   6.24153E18*2.4E-9*1312*5 ==> 9.8266E13 e-/sec
*      or 2625 bunches/pulse ==> 1.966E14 e-/sec
*
*   5000 hours/year operation ( ~208 days/year )
*   ===> 5000*3600=18000000 sec
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*3760
* * replaced ** what.3=3600*5000
* * replaced ** what.4=9.84E13*2
* * replaced ** what.5=3600*3760
IRRPROFI   13536000.       0.0 18000000.  1.968E14 13536000.       0.0
*
* Definition of irradiation pattern for 1312/2625 bunches per pulse
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8
*         5000 hours    part/s
* * replaced ** what.1=3600*5000
* * replaced ** what.2=9.84E13*2
* * replaced ** what.3=3600*3760
* * replaced ** what.5=3600*5000
* * replaced ** what.6=9.84E13*2
IRRPROFI   18000000.  1.968E14 13536000.       0.0 18000000.  1.968E14
